### PR TITLE
Removes PublicAnMaid: Maid 1053

### PR DESCRIPTION
**Pull request by mmoadeli**
what is done in the PR
1- Removes PublicAnMaid.rs
2- Adds revocation_public_key as a member of public_maid and public_mpid
3- minor clean up

Please note in order to keep the PRs review-able, the issues regarding proper name creation (which is asked to be done by David) will done in other tasks.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_types/48)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/id/public_mpid.rs, line 36 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48#-Jq5ktz5ysSByovRlZ7h)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37ff723948b1167bb755a71f600510a30ccfca37/src/id/public_mpid.rs#L36)):</sup>
As this is now exactly the same as public_maid with the the exception that it holds a different tag value should we not be considering reducing this code dramatically and  have a ID type that pmid maid etc. as well as public couterparts are all derived from. It seems a pretty large duplication of code here and we know what we code we can break, so perhaps consider reducing this to an ID type and use a u64 template parameter to create the specific types we want? 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Comment by dirvine** [comment]
I think we can dramatically reduce code here using an ID and Public Id types with the corresponding revocation types. Lets look a bit closer at that as it will make things much simpler. 

---

Review status: 0 of 5 files reviewed, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Comment by mmoadeli** [comment]
Agreed, thanks

---

Review status: 0 of 5 files reviewed, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Comment by dirvine** [comment]
Cool, It also makes our types extensible as app devs can create their own ID types with just a bit more work by us here. I can see this become an important area. 

---

Review status: 0 of 5 files reviewed, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Comment by dirvine** [comment]
Is the intention here to not have an id type that can create maid/mpid etc. now? We still have a ton of duplication!

---

Review status: 0 of 7 files reviewed, 1 unresolved discussion, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Comment by mmoadeli** [comment]
I did so for Public types only

**Comment by dirvine** [comment]
Ok, lets get the docs 100% and then we can get the code in place to match :-) 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- Cargo.toml @ r2
- src/id/mod.rs @ r2
- src/id/public_an_maid.rs @ r1
- src/id/public_id_type.rs @ r3
- src/id/public_maid.rs @ r2
- src/id/public_mpid.rs @ r2
- src/lib.rs @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/48)

**Pull request merged**
