### PR TITLE
Cleaned up PublicAnMaid, and strengthened all id deserialisation tests.

### PR DESCRIPTION
**Pull request by vtnerd**
Check `PublicAnMaid` closely. It now only contains a public key (from `AnMaid`), and a signature from the private key of the same `AnMaid`. The public key is considered to be the owner of the `PublicAnMaid`. The name is the hash of the public key (owner).

This also validates on each de-serialisation that the self-signed value is correct, and has a function for verifying that `AnMaid` owns a particular `PublicAnMaid`.

However - what exactly is this used for? The `PublicMaid` for example would have the same owner as this type presumably (the `AnMaid` public key), and the `PublicMaid` could only be de-authorized by having the private key from `AnMaid` sign a request to do so. This is only useful if you limit the puts for `PublicAnMaid`, and therefore a `PublicMaid` wouldn't be valid until the limited `PublicAnMaid` was posted. Is that the idea? Its just not clear why this needs to exist in addition to `PublicMaid` - only one would seem necessary.

Anyway let me know of updates necessary.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_types/33)

### CODE REVIEW

**Comment by dirvine** [comment]
I will let @Fraser999 take a look at this now @vtnerd . I did notice though a lot of unsafe blocks and also naked unwrap() statements. Do you not think we should look at not having naked unwrap() calls and unsafe blocks a bit further? It seems/feels like the most fragile of all the code so far in terms of ability to crash.

**Comment by vtnerd** [comment]
Theres no `unsafe` blocks in this patch - unless you count the one being removed. And theres one naked `unwrap()` that could lead to program termination if the invariant listed in the documentation is _not_ held. I was mixed on that, since theres no way to guarantee that sodiumoxide produces a signature larger than `SIGNATUREBYTES`, and no way to enforce the caller of the function provide a vector from the sodiumoxide `sign` function. I can make this an `Option<>` return, which is probably the right thing to do, but then the creation function for `PublicAnMaid` can fail, when _basically_ it cannot.

The other `unwrap()` calls are in either in tests, or checked using `is_none()` before the unwrap. I chose not to do any binding in that one case, but I can change to that style if desired.

**Comment by dirvine** [comment]
Yes I would change to `Option<>` return and also worth taking time over the existing unsafe blocks in the macro code from last week. I suspect this could bite us at some stage. I did note there is some activity in array handling going into rust at last which will be nice and help. It's here  https://github.com/rust-lang/rust/blob/master/src/libcore/array.rs so en route but not yet. 

If you can figure ways to remove all unsafe blocks then it will help though as these are us telling the compiler to leave us alone and I prefer not to do that unless we are totally stuck then we should ask on the forums for ways around it or end up doing PR to rust language.

**Comment by vtnerd** [comment]
###### The "Unsafe" Block

I don't see anything wrong with that `unsafe` block. There is already a test that uses an object with a destructor, which tests the worse case scenario. All its doing is saying "don't initialize these bytes", then memcpying the valid values in, while ignoring the uninitialized values that were originally present. `mem::replace` and `mem::forget` would have to change in their stated behavior for that to be an issue - a lot of code I've see in the stdlib would bomb in that situation. They'd just change the names most likely at that point.

The problem is that this language has no default-construct concept, so theres no alternative except hard-coding the type to `u8` in the array internally and initalizing everything to zero. You then lose the generic behavior of the macro entirely, and get a funky expansion error in that situation (the error isn't terribly hard to read at least). Since its not being used for anything else we can do that, but then it wouldn't even work for usize types, etc, which is also a shame - I don't like code duplication.

###### Signature

I should've returned an `Option` in the `detach_signature`, but what about the `PublicAnMaid::new`? It wouldn't be possible to write a test that could fail currently (unless you count the abortion due to `malloc` failure). It would be forcing error handling on the client, when it could never fail, and no effective strategy for handling a "sodiumoxide has altered its signature behavior error". I can do it though, and I guess let it bubble up in case someone figures out how to handle that.

**Comment by dirvine** [comment]
" hard-coding the type to u8 in the array internally and initializing everything to zero" The choice between this and an unsafe block for me at the moment is a no brainer. 
The maidsafe_ libs are ours and not generic anyway. so I suggest this at least for the time being. I really do not want unsafe blocks anywhere until we are expert enough to be certain all is well and there is no other way. I agree if we were creating a generic type here then that would not be great, but I am also sure we will have other options as well, not that we need them at the moment.

**Comment by vtnerd** [comment]
The macro was copied into routing by someone, although it doesn't appear to be exported. The current copy+paste duplication can't be removed without exporting the macro from routing. Guess I'll just change both until someone figures out whether they want to remove that duplication.

**Comment by vtnerd** [comment]
Changed the macro to remove `unsafe` blocks.

The `PublicAnMaid::new` can now "fail". This seems to be the behavior you want, but keep in mind this isn't a runtime-failure that can be induced, its a broken invariant between the signing functions. If it breaks the error will get pushed up the stack to some other location, and could make it harder to track the source of the issue. That was largely my point of making it bomb inside of the `detatch` function previously - the signature should've never come from an untrusted source. Although arguably someone could eventually want to `detach` a signature from de-serialised bytes (don't know why, the verify function does this + verifies). Doesn't seem bad to make it a recoverable error in `detach` (since someone _might_ use it for data from an untrusted source in the future), but this is now a broken invariant in `AnMaid` being bubbled up the call stack. If thats what you want, there you go.

**Pull request closed without merging**
