### PR TITLE
ChangeLog / ReadMe

### PR DESCRIPTION
**Pull request by mmoadeli**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_types/46)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
@mmoadeli: no appropriate reviewer found, use r? to override

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: 0 of 2 files reviewed, all discussions resolved, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by dirvine** [comment]
conflicts ?

---

Review status: 0 of 2 files reviewed, all discussions resolved, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by dirvine** [comment]
With the changes for invariance and tags for security, I have a question. Can the AnPublicXXX types actually now be included as part of the body of the PublicType, therefore reducing number of types and allowing in place validation. N.B. the signature of the content pre hash, allows a fix to be made on the included types and prevent replacement which may have same hash, the signature puts this out of the realms of possibility. Otherwise it may be possible to swap keys continually with the tag_id which although is inordinately unlikely, the signature simply makes it computationally infeasible. 

---

Review status: 0 of 2 files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 17 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-Jpih-z60Tx68N2cXtq7)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L17)):</sup>
The purpose of this is not to obtain name() but to use it as a way of ensuring type invariance, this seems significantly more important. 

---

<sup>**[README.md, line 18 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpihE7liScKhI_AQr_J)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L18)):</sup>
signature creations ? does not make sense. Perhaps you mean ID type creation

---

<sup>**[README.md, line 20 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpihPmtpgUNAwk4lm4b)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L20)):</sup>
Each data types here is a vector<T> which is generally of size 1. This allows multi-sig and escrow capabilities.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by dirvine** [comment]
Review status: 0 of 2 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 21 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-Jpiisl1ChpIjQ5G5CCg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L21)):</sup>
Does this allow replacement attacks as mentioned in comment (unlikely but does reduce security)? 

---

<sup>**[README.md, line 22 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpiiiqyGTzrYa27v1eV)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L22)):</sup>
signatures here seems irrelevant as it's all types to us, some of which contain a signature. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by mmoadeli** [comment]
Review status: 0 of 2 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 17 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-Jpih-z60Tx68N2cXtq7)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L17)):</sup>
Ok

---

<sup>**[README.md, line 18 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpihE7liScKhI_AQr_J)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L18)):</sup>
An element of the input to signature is Type tag. Other elements are public keys and owner_signing_public_key for dependent keys. and public keys for pure keys

---

<sup>**[README.md, line 20 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpihPmtpgUNAwk4lm4b)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L20)):</sup>
Ok. I change it

---

<sup>**[README.md, line 21 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-Jpiisl1ChpIjQ5G5CCg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L21)):</sup>
very very unlikely. The combination of signature and then Hash should make it strong enough.

---

<sup>**[README.md, line 22 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46#-JpiiiqyGTzrYa27v1eV)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f5189426078083c94d7f70abfe76a1f682b9ee7b/README.md#L22)):</sup>
Ok

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by mmoadeli** [comment]
Presenting them as one type is a very good idea. I add it as a task then, if it is ok.

---

Review status: 0 of 2 files reviewed, 5 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Comment by dirvine** [comment]
Also need to update diagrams Shona is doing

---

Review status: 0 of 2 files reviewed, all discussions resolved, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/46)

**Pull request merged**
