### PR TITLE
MAID-1029, MAID-1035, MAID-1041 and MAID-1058 

### PR DESCRIPTION
**Pull request by mmoadeli**
The PR addresses MAID-1029, MAID-1035, MAID-1041 and MAID-1058 tasks.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_types/54)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maidsafe-highfive** [comment]
Windows Build Successful

**Comment by maidsafe-highfive** [comment]
OS X Build Successful

**Comment by dirvine** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper.rs, line 59 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54#-JqKiUvP0WfIBo78tvMg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/2058d266c6a1c7eb6c628448f62a7a7fa5bd99ae/src/helper.rs#L59)):</sup>
Where is sig optional? 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by mmoadeli** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper.rs, line 59 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54#-JqKiUvP0WfIBo78tvMg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/2058d266c6a1c7eb6c628448f62a7a7fa5bd99ae/src/helper.rs#L59)):</sup>
because the function can be used with Revocation and Id types as well as PublicITypes. Only PublicIdTypes have signature

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by mmoadeli** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper.rs, line 59 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54#-JqKiUvP0WfIBo78tvMg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/2058d266c6a1c7eb6c628448f62a7a7fa5bd99ae/src/helper.rs#L59)):</sup>
used by ...

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by dirvine** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper.rs, line 59 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54#-JqKiUvP0WfIBo78tvMg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/2058d266c6a1c7eb6c628448f62a7a7fa5bd99ae/src/helper.rs#L59)):</sup>
But those types surely are different. Revocation key is a keypair (signing keys) and Id types are two keypairs (sign + encrypt). There very different indeed.  These are privately held keytypes now and validated by checking the keypairs is a cryptographic check - no no need to hash etc. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by dirvine** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- src/helper.rs @ r1
- src/id/an_maid.rs @ r1
- src/id/an_mpid.rs @ r1
- src/id/id_type.rs @ r1
- src/id/maid.rs @ r1
- src/id/mod.rs @ r1
- src/id/mpid.rs @ r1
- src/id/public_id_type.rs @ r1
- src/id/revocation_id_type.rs @ r1
- src/lib.rs @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by ustulation** [comment]
just a question: should IdType have a public function to return secret keys too (like it has for returning public keys)? If no then there isn't a way i can give it to routing here
https://github.com/maidsafe/routing/blob/master/src/routing_client.rs#L67

So in that case the Routing libraries way of working will have to change too. So what is correct - returning private keys or not-returning them ?

**Comment by mmoadeli** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper.rs, line 59 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54#-JqKiUvP0WfIBo78tvMg)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/2058d266c6a1c7eb6c628448f62a7a7fa5bd99ae/src/helper.rs#L59)):</sup>
Correct.  Id types can use it though as they have pair of keys. I can make in non-optional

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Comment by dirvine** [comment]
Yes @ustulation This is a requirement. The Id and Revocation types will need refactored anyway, but for now this does need to be able to return secret keys, otherwise we cannot sign or encrypt anything with them.

**Comment by mmoadeli** [comment]
I add it as a function.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/54)

**Pull request merged**
