### PR TITLE
Maid 1029: Removes name as a member variable from types

### PR DESCRIPTION
**Pull request by mmoadeli**
1- Removes name as a member variable from types.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_types/47)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by mmoadeli** [comment]
Please note that the computation of name, in get_name functions will be changed once all fields are added to the types

**Comment by dirvine** [comment]
I have made some comments which will repeat through all types. IT is hard to see what we are doing without the full types as per the diagrams (one diagram per type that describes full;y the type) that should by now be on front page (in README.md) file. Not prioritising that means this lib is not easy to understand or follow. 

---

Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks failed.
Reviewed files:
- src/data/structured_data.rs @ r1

---

<sup>**[src/helper.rs, line 58 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqioyT1ZJJEXaz0p_m)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f755ebb06d5fbcb269b156cd7e97e007a9b9cc78/src/helper.rs#L58)):</sup>
Should this not just be called `name` IT is a function so the word calculate is perhaps implicit

---

<sup>**[src/id/an_mpid.rs, line 55 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqk1CGFUNs3mKSW1sc)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L55)):</sup>
Here we use get_name() instead of name() ? Perhaps think about a single naming convention ? I would think name() is good enough.

---

<sup>**[src/id/an_mpid.rs, line 83 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqjIjUYuA1zKQTdeAO)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L83)):</sup>
Should this be an option, seems we cannot now have a name == None
Also perhaps return a borrow ? to save a copy

---

<sup>**[src/id/an_mpid.rs, line 105 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqjk0g-05Awln0aVEw)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L105)):</sup>
I am not sure removing the name is valid, seems if the name is invariant then a Eq implementation would simply check type and name. This is a potential security leak

---

<sup>**[src/id/mpid.rs, line 65 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqkL4orjZYrLPye2Ma)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/mpid.rs#L65)):</sup>
Same here if we check the invariants it's very powerful, especially as they are cryptographically secured invariants. so removing name() == name() is perhaps a security leak as it's less secure to ignore the crypto invariant.

---

<sup>**[src/id/mpid.rs, line 77 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqkbaHMFlQy9FgJNoN)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f755ebb06d5fbcb269b156cd7e97e007a9b9cc78/src/id/mpid.rs#L77)):</sup>
Again get_name() as opposed to name()

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
Type tag missing from these types. 

---

Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by mmoadeli** [comment]
David, regarding the diagrams I am with you on this as I constantly look at the tables describing them. If we can put up with them till Monday, I will come up with some diagrams for each.

Regarding the Type-Tag, my impression was that as implementation of sendable for each type returns a const there will be no need for that. I add them, if you really believe they are required.

---

Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks failed.

---

<sup>**[src/helper.rs, line 58 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqioyT1ZJJEXaz0p_m)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f755ebb06d5fbcb269b156cd7e97e007a9b9cc78/src/helper.rs#L58)):</sup>
Ok

---

<sup>**[src/id/an_mpid.rs, line 55 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqk1CGFUNs3mKSW1sc)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L55)):</sup>
I used get_name in Types as all other functions started with get _... . Also, as Sendable has name as a function it will cause confusion and probably not even compile. I can  remove them as they are in Sendable

---

<sup>**[src/id/an_mpid.rs, line 83 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqjIjUYuA1zKQTdeAO)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L83)):</sup>
Sorry David, I don't get your point on this

---

<sup>**[src/id/an_mpid.rs, line 105 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqjk0g-05Awln0aVEw)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L105)):</sup>
I put name back in this type. Not fully convinced they are required though. 

---

<sup>**[src/id/mpid.rs, line 65 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqkL4orjZYrLPye2Ma)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/mpid.rs#L65)):</sup>
again I put it back. What I am missing is that, Name is Hash of public keys, if the public keys are compared what is the need to compare their hashes.  

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks failed.

---

<sup>**[src/id/mpid.rs, line 65 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqkL4orjZYrLPye2Ma)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/mpid.rs#L65)):</sup>
Their needs to be a type tag and the hash will include this, which will be different, only using public keys is very hackable. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks failed.

---

<sup>**[src/id/an_mpid.rs, line 83 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqjIjUYuA1zKQTdeAO)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L83)):</sup>
My bad here Mahmoud I seen option NameType and though it was optional name. So it is correct not all types have owner.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by Fraser999** [comment]
Review status: 1 of 9 files reviewed, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/id/an_mpid.rs, line 55 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqk1CGFUNs3mKSW1sc)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L55)):</sup>
Getters shouldn't start with "get_"  http://aturon.github.io/style/naming/README.html#getter/setter-methods-[rfc-344]  I'd vote to rename the rest as well.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by mmoadeli** [comment]
Review status: 0 of 10 files reviewed, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/id/an_mpid.rs, line 57 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpqk1CGFUNs3mKSW1sc)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/37a1b5f10df68f4c80b77c81108c62abe032e2fe/src/id/an_mpid.rs#L57)):</sup>
Thanks Admiral.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
Review status: 0 of 10 files reviewed, 7 unresolved discussions, some commit checks failed.

---

<sup>**[src/data/immutable_data.rs, line 35 [r7]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-Jpsh4yhe3_5YgGTRoC3)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/08b218f2a050ff0c595c70b70143f9b47b69e001/src/data/immutable_data.rs#L35)):</sup>
This needs to include type tag otherwise it can be spoofed / hacked - especially so for id packets as well.  Hash of value alone is certainly not enough. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
Review status: 0 of 10 files reviewed, 7 unresolved discussions, some commit checks failed.

---

<sup>**[src/helper.rs, line 58 [r3]](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47#-JpqioyT1ZJJEXaz0p_m)** ([raw file](https://github.com/maidsafe/maidsafe_types/blob/f755ebb06d5fbcb269b156cd7e97e007a9b9cc78/src/helper.rs#L58)):</sup>
Again if this does not contain the type tag it can be spoofed, i.e. I can tell you a PublicMaid is a PublicMpid and you cannot tell as it's all valid (all I need to is change the tag and the invariant holds, i.e. it's not an invariant)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
When deriving name() then you must include the type_tag in hash statements otherwise it's not an invariant, this holds true for all types where we use hashes like this. I commented a couple, but that's a pretty large security leak and would allow a security leak for sure. 

---

Review status: 0 of 10 files reviewed, 7 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by mmoadeli** [comment]
Maybe it is better to have a signature and not the hash. Also, these are not part of this task. I have already changed the task description once. Maybe it can be addressed in type invariance check test. Or the one which is about ensuring all types conform to  drawn presentation.

---

Review status: 0 of 10 files reviewed, 7 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by dirvine** [comment]
I will merge this mahmoud as it's now a monstor PR and does have security flaws. Can you please ensure all of these are fixed this sprint by other tasks. PR's longer than a few lines are near impossible to review so please keep the size down or split tasks if it grows too big.  Coverage is extremely concerning as well so now this library is not secure, has low coverage and in a state of confusion, we need to fix this today I think.

---

Review status: all files reviewed, 7 unresolved discussions, some commit checks failed.
Reviewed files:
- src/data/immutable_data.rs @ r7
- src/data/structured_data.rs @ r7
- src/helper.rs @ r4
- src/id/an_maid.rs @ r6
- src/id/an_mpid.rs @ r6
- src/id/maid.rs @ r6
- src/id/mpid.rs @ r6
- src/id/public_an_maid.rs @ r6
- src/id/public_maid.rs @ r6
- src/id/public_mpid.rs @ r6

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_types/47)

**Comment by mmoadeli** [comment]
David, I have the diagrams ready very soon. Certainly we sort it out today.

**Pull request merged**
